workflows:
  ios-swiftui-workflow:
    name: iOS SwiftUI Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build iOS App
        script: |
          xcodebuild build -scheme ControleTerritorios -sdk iphoneos
    artifacts:
      - build/ios/ipa/*.ipa
